version: '3.9'

services:

  backend-miko-marketplace:
    user: $UID
    command: npm run dev
    build:
      context: ./mikomarketplace-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: marketplace-api
    environment:
      MONGO_HOST: localhost
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
      MONGO_PORT: 27017
      MONGO_DATABASE: biobank_auth
    volumes: 
      - ./mikomarketplace-backend:/mikomarketplace-backend
    networks:
      - miko-marketplace-network

  frontend-miko-marketplace:
    build:
      context: ./mikomarketplace-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    container_name: marketplace-ui
    volumes:
      - './mikomarketplace-frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    networks:
      - miko-marketplace-network

  mongo:
    user: $UID
    image: mongo
    ports:
      - "27017:27017" 
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
      MONGO_INITDB_DATABASE: miko_marketplace
    volumes:
      - ./.mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: on-failure
    networks:
      - miko-marketplace-network

networks:
  miko-marketplace-network:
    driver: bridge