version: '3.9'

services:

  backend-miko-marketplace:
    user: $UID
    command: bash -c "/mikomarketplace-backend/wait-for-it.sh --timeout=0 mongo:27017 && npm run dev"
    build:
      context: ./mikomarketplace-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    container_name: marketplace-api
    environment:
      NODE_ENV: development
      MONGO_HOST: mongo
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
      MONGO_PORT: 27017
      MONGO_DATABASE: mikomarketplace
    volumes: 
      - ./mikomarketplace-backend:/mikomarketplace-backend
      - /mikomarketplace-backend/node_modules
    networks:
      - miko-marketplace-network
    restart: on-failure:5 

  frontend-miko-marketplace:
    build:
      context: ./mikomarketplace-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    container_name: marketplace-ui
    volumes:
      - './mikomarketplace-frontend:/app'
      - '/app/node_modules'
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    networks:
      - miko-marketplace-network
    restart: on-failure:5 

  mongo:
    user: $UID
    image: mongo
    ports:
      - "27017:27017" 
    container_name: mongo
    volumes:
      - ./.mongo-data:/data/db
    restart: on-failure
    networks:
      - miko-marketplace-network
    restart: on-failure:5

volumes:
  .mongo-data:

networks:
  miko-marketplace-network:
    driver: bridge