version: '3.9'

services:

  frontend-miko-marketplace:
  container_name: frontendcontainer
  build: ./frontend-miko-marketplace
  volumes:
    - './frontend-miko-marketplace:/usr/src/app'
  ports:
    - '4200:4200'
  networks:
    - miko-marketplace-network
  command: >
    bash -c "ng serve --host 0.0.0.0 --port 4200"

  mongo:
    user: $UID
    image: mongo
    container_name: mongodb 
    ports:
      - "27017:27017" 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
      MONGO_INITDB_DATABASE: miko_marketplace
    volumes:
      - ./.mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: on-failure
    networks:
      - miko-marketplace-network

networks:
  miko-marketplace-network:
    driver: bridge